[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/mouryarahul/7CS107_PracticalWorks_Assignment/blob/master/Week2_Assignment.ipynb)


# Week 2 Assignment — Linear Algebra for AI (Programming)

**Module:** Advanced Artificial Intelligence & Machine Learning (MSc)  
**Topic:** Mathematical Foundations for AI — Linear Algebra Review  
**Instructions:**  
- Complete each problem in order. Do **not** use high-level NumPy linear algebra helpers unless the prompt
  explicitly allows it for verification.  
- For each function, write minimal tests and print results as indicated.  
- Keep your code clean and well-documented.  
- Marks: **10 or 20 per problem** (correctness + clarity + simple tests).  


In [1]:

# You may use NumPy for arrays and basic operations; avoid calling high-level linalg unless allowed.
import numpy as np

np.set_printoptions(precision=4, suppress=True)
rng = np.random.default_rng(42)



## Problem 1 (10 Marks): Matrix Multiplication (loops only)

Implement `matrix_multiply(mat1, mat2)` using **basic operations and loops** (no `np.dot`/`@`/`np.matmul`).  
Verify by comparing with `np.matmul` on two small random matrices (e.g., 3×2 and 2×3).


In [36]:

def matrix_multiply(mat1, mat2):
    """
    Multiply two 2D numpy arrays using explicit loops.
    Inputs: mat1 (m x k), mat2 (k x n)
    Output: result (m x n)
    """
    A = np.asarray(mat1)
    B = np.asarray(mat2)
    m, k1 = A.shape
    k2, n = B.shape
    assert k1 == k2, "Inner dimensions must match for multiplication."
    # My code goes here
    # Initialize result matrix with zeros
    result = np.zeros((m, n), dtype=float)
    # Triple nested loops
    for i in range(m):
        for j in range(n):
            s = 0.0
            for t in range(k1):
                s += A[i, t] * B[t, j]
            result[i, j] = s
    return result

# --- Test ---
mat1 = rng.normal(size=(3, 2))
mat2 = rng.normal(size=(2, 3))
res_ref = np.matmul(mat1, mat2)
res_my  = matrix_multiply(mat1, mat2)
print("np.matmul:\n", res_ref)
print("matrix_multiply:\n", res_my)
print("max abs diff:", np.max(np.abs(res_ref - res_my)))


np.matmul:
 [[ 0.2654  0.4354 -0.0306]
 [ 0.2224 -0.2091  0.4508]
 [-1.6984  0.3472 -2.405 ]]
matrix_multiply:
 [[ 0.2654  0.4354 -0.0306]
 [ 0.2224 -0.2091  0.4508]
 [-1.6984  0.3472 -2.405 ]]
max abs diff: 2.220446049250313e-16



## Problem 2 (20 Marks): Dot Product & Angle Between Vectors

Write two functions without using `np.dot`:
- `dot(u, v)` returning the scalar dot product,
- `angle(u, v)` returning the angle (in radians) between `u` and `v`.

**Verify:** Compare `dot(u, v)` to `np.dot(u, v)` and check that `angle(u, v)` is ~`np.arccos(np.dot(u,v)/(||u||·||v||))`.


In [37]:

def dot(u, v):
    u = np.asarray(u).ravel()
    v = np.asarray(v).ravel()
    assert u.shape == v.shape, "Vectors must have same length."
    # My code goes here
    # simple elementwise product sum
    result = 0.0
    for a, b in zip(u, v):
        result += a * b
    return result

def angle(u, v):
    u = np.asarray(u).ravel()
    v = np.asarray(v).ravel()
    assert u.shape == v.shape, "Vectors must have same length."
    # My code goes here
    denom = np.linalg.norm(u) * np.linalg.norm(v)
    if denom == 0:
        raise ValueError("Angle is undefined for zero-length vectors.")
    # clip to [-1,1] to avoid numerical issues
    cos_theta = dot(u, v) / denom
    cos_theta = max(-1.0, min(1.0, cos_theta))
    result = np.arccos(cos_theta)
    return result

# --- Test ---
u = rng.normal(size=5)
v = rng.normal(size=5)
print("dot:", dot(u, v), " vs np.dot:", np.dot(u, v))
print("angle (rad):", angle(u, v))


dot: -0.3632682773973761  vs np.dot: -0.3632682773973761
angle (rad): 1.930123010279131



## Problem 3 (20 Marks): Vector & Matrix Norms

Implement without `np.linalg.norm`:
- `l1_norm(x)`, `l2_norm(x)`, `linf_norm(x)` for vectors,
- `frobenius_norm(A)` for matrices.

**Verify:** Compare results to `np.linalg.norm` for random vectors/matrices.


In [38]:

def l1_norm(x):
    x = np.asarray(x).ravel()
    # My code goes here
    # sum of absolute values
    result = 0.0
    for xi in x:
        result += abs(float(xi))
    return result

def l2_norm(x):
    x = np.asarray(x).ravel()
    # My code goes here
    s = 0.0
    for xi in x:
        s += float(xi)**2
    return float(np.sqrt(s))

def linf_norm(x):
    x = np.asarray(x).ravel()
    # My code goes here
    if x.size == 0:
        return 0.0
    maxv = 0.0
    for xi in x:
        val = abs(float(xi))
        if val > maxv:
            maxv = val
    return maxv

def frobenius_norm(A):
    A = np.asarray(A)
    # My code goes here
    s = 0.0
    for val in A.ravel():
        s += float(val)**2
    return float(np.sqrt(s))

# --- Test ---
x = rng.normal(size=7)
A = rng.normal(size=(4, 3))
print("L1:", l1_norm(x), " vs ", np.linalg.norm(x, 1))
print("L2:", l2_norm(x), " vs ", np.linalg.norm(x, 2))
print("Linf:", linf_norm(x), " vs ", np.linalg.norm(x, np.inf))
print("Fro:", frobenius_norm(A), " vs ", np.linalg.norm(A, "fro"))


L1: 9.362551598327032  vs  9.362551598327032
L2: 3.8737015307402545  vs  3.8737015307402545
Linf: 2.3336161198483047  vs  2.3336161198483047
Fro: 3.0130351515528377  vs  3.0130351515528377



## Problem 4 (10 Marks): Projection Onto a Vector (and Decomposition)

Implement `proj(u, v)` = projection of vector `u` onto `v`. Also return the decomposition `u = u_parallel + u_perp`  
where `u_parallel = proj(u, v)` and `u_perp = u - u_parallel`.

**Verify:** Check `u_parallel` is parallel to `v` and `u_perp` is orthogonal to `v` (their dot product is ~0).


In [43]:

def proj(u, v):
    u = np.asarray(u).ravel()
    v = np.asarray(v).ravel()
    # My code goes here
    v_norm_sq = dot(v, v)
    if v_norm_sq == 0:
        # projection onto zero vector is zero vector of same shape
        return np.zeros_like(u)
    coeff = dot(u, v) / v_norm_sq
    result = coeff * v
    return result

# --- Test ---
u = rng.normal(size=5)
v = rng.normal(size=5)
u_par = proj(u, v)
u_perp = u - u_par
print("dot(v, u_perp) ~ 0:", dot(v, u_perp))


dot(v, u_perp) ~ 0: -8.673617379884035e-17



## Problem 5 (20 Marks): Determinant (2×2 and 3×3) & Volume Intuition

Implement `det2(A)` and `det3(A)` using closed-form expressions.  
**Verify:** Compare to `np.linalg.det` (rounded) on random integer matrices.


In [47]:

def det2(A):
    A = np.asarray(A, dtype=float)
    assert A.shape == (2, 2)
    return A[0,0]*A[1,1] - A[0,1]*A[1,0]

def det3(A):
    A = np.asarray(A, dtype=float)
    assert A.shape == (3, 3)
    a,b,c = A[0]
    d,e,f = A[1]
    g,h,i = A[2]
    return a*(e*i - f*h) - b*(d*i - f*g) + c*(d*h - e*g)

# --- Test ---
A2 = rng.integers(-5, 6, size=(2,2))
A3 = rng.integers(-3, 4, size=(3,3))
print("det2 vs np:", det2(A2), " vs ", round(np.linalg.det(A2)))
print("det3 vs np:", det3(A3), " vs ", round(np.linalg.det(A3)))


det2 vs np: -6.0  vs  -6
det3 vs np: 42.0  vs  42



## Problem 6 (20 Marks): Least Squares via Pseudoinverse (SVD)

Implement `pinv(A)` using `np.linalg.svd`. Use it to solve linear regression `x* = pinv(A) @ b` and report residual norm `||Ax* - b||_2`.

**Verify:** Compare with `np.linalg.lstsq(A, b, rcond=None)`.


In [ ]:

def pinv(A, tol=1e-12):
    A = np.array(A, dtype=float)
    U, S, VT = np.linalg.svd(A, full_matrices=False)
    S_inv = np.array([1/s if s > tol else 0.0 for s in S])
    return (VT.T * S_inv) @ U.T

# --- Test ---
m, n = 8, 5
A = rng.normal(size=(m, n))
x_true = rng.normal(size=n)
b = A @ x_true + 0.01 * rng.normal(size=m)  # small noise
x_pinv = pinv(A) @ b
x_ls, *_ = np.linalg.lstsq(A, b, rcond=None)
print("Residual (pinv):", np.linalg.norm(A@x_pinv - b))
print("Residual (lstsq):", np.linalg.norm(A@x_ls - b))


Residual (pinv): 0.011547416124392484
Residual (lstsq): 0.011547416124392343
